name: CI

on: [push]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config: 
        - {
            name: "Windows Latest x64", artifact: "Windows-x64.zip",
            os: windows-latest,
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          }
        - {
            name: "Windows Latest x86", artifact: "Windows-x86.zip",
            os: windows-latest,
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars32.bat"
          }

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup env
      run: {{ matrix.config.environment_script }}

    - name: Download files
      run: qt download

    - name: OpenSSL
      run: qt openssl
      
    - name: Setup
      run: qt setup

    -name: Build
     run: qt build
     
      
